# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_capcture.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_right_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_right_save.setGeometry(QtCore.QRect(560, 450, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_right_save.setFont(font)
        self.pushButton_right_save.setObjectName("pushButton_right_save")
        self.pushButton_left_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_left_save.setGeometry(QtCore.QRect(110, 450, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_left_save.setFont(font)
        self.pushButton_left_save.setObjectName("pushButton_left_save")
        self.left_camera = QtWidgets.QGroupBox(self.centralwidget)
        self.left_camera.setGeometry(QtCore.QRect(20, 50, 461, 391))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.left_camera.setFont(font)
        self.left_camera.setObjectName("left_camera")
        self.label_camera_left = QtWidgets.QLabel(self.left_camera)
        self.label_camera_left.setGeometry(QtCore.QRect(10, 40, 440, 330))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_camera_left.setFont(font)
        self.label_camera_left.setAlignment(QtCore.Qt.AlignCenter)
        self.label_camera_left.setObjectName("label_camera_left")
        self.right_camera = QtWidgets.QGroupBox(self.centralwidget)
        self.right_camera.setGeometry(QtCore.QRect(480, 50, 461, 391))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.right_camera.setFont(font)
        self.right_camera.setObjectName("right_camera")
        self.label_camera_right = QtWidgets.QLabel(self.right_camera)
        self.label_camera_right.setGeometry(QtCore.QRect(10, 40, 440, 330))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_camera_right.setFont(font)
        self.label_camera_right.setAlignment(QtCore.Qt.AlignCenter)
        self.label_camera_right.setObjectName("label_camera_right")
        self.pushButton_left_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_left_open.setGeometry(QtCore.QRect(90, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_left_open.setFont(font)
        self.pushButton_left_open.setObjectName("pushButton_left_open")
        self.pushButton_right_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_right_open.setGeometry(QtCore.QRect(560, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_right_open.setFont(font)
        self.pushButton_right_open.setObjectName("pushButton_right_open")
        self.pushButton_left_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_left_close.setGeometry(QtCore.QRect(260, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_left_close.setFont(font)
        self.pushButton_left_close.setObjectName("pushButton_left_close")
        self.pushButton_right_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_right_close.setGeometry(QtCore.QRect(730, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_right_close.setFont(font)
        self.pushButton_right_close.setObjectName("pushButton_right_close")
        self.label_logs_left = QtWidgets.QLabel(self.centralwidget)
        self.label_logs_left.setGeometry(QtCore.QRect(110, 490, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_logs_left.setFont(font)
        self.label_logs_left.setText("")
        self.label_logs_left.setObjectName("label_logs_left")
        self.label_logs_right = QtWidgets.QLabel(self.centralwidget)
        self.label_logs_right.setGeometry(QtCore.QRect(560, 490, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_logs_right.setFont(font)
        self.label_logs_right.setText("")
        self.label_logs_right.setObjectName("label_logs_right")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_right_save.setText(_translate("MainWindow", "Save Right Camera Image"))
        self.pushButton_left_save.setText(_translate("MainWindow", "Save Left Camera Image"))
        self.left_camera.setTitle(_translate("MainWindow", "Left Camera"))
        self.label_camera_left.setText(_translate("MainWindow", "left"))
        self.right_camera.setTitle(_translate("MainWindow", "Right Camera"))
        self.label_camera_right.setText(_translate("MainWindow", "right"))
        self.pushButton_left_open.setText(_translate("MainWindow", "Open Left Camera"))
        self.pushButton_right_open.setText(_translate("MainWindow", "Open Right Camera"))
        self.pushButton_left_close.setText(_translate("MainWindow", "Close Left Camera"))
        self.pushButton_right_close.setText(_translate("MainWindow", "Close Right Camera"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

